/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FactureForm.java
 *
 * Created on Jun 27, 2012, 7:51:14 PM
 */

package hotel.gui;

import hotel.Agenda;
import hotel.Hotel;
import hotel.Room;
import hotel.Stay;
import hotel.TaxesSystem;

import java.util.Date;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author AJ86290
 */
public class FactureForm extends javax.swing.JFrame {

    /** Creates new form FactureForm */
    public FactureForm() {
    	GUI.initLookAndFeel();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableChamberList = new javax.swing.JTable();
        ButtonAdd = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();
        ButtonOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelSubtotal = new javax.swing.JLabel();
        LabelTPS = new javax.swing.JLabel();
        LabelTVQ = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableChamberList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro de chambre", "Catégorie", "Nombre de jours", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
        jScrollPane1.setViewportView(TableChamberList);
        TableChamberList.getColumnModel().getColumn(0).setResizable(false);
        TableChamberList.getColumnModel().getColumn(1).setResizable(false);
        TableChamberList.getColumnModel().getColumn(2).setResizable(false);
        TableChamberList.getColumnModel().getColumn(3).setResizable(false);

        ButtonAdd.setText("+");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					ButtonAddActionPerformed(evt);
				} catch (Exception e) {
					JOptionPane.showMessageDialog(null, "Aucun séjour actif n'existe pour cette chambre.");
				}
            }
        });

        ButtonDelete.setText("-");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonCancel.setText("Annuler");
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        ButtonOk.setText("Ok");
        ButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOkActionPerformed(evt);
            }
        });

        jLabel1.setText("TPS:");

        jLabel2.setText("Sous-total:");

        jLabel3.setText("TVQ:");

        jLabel4.setText("Total:");

        LabelSubtotal.setText("0.00$");

        LabelTPS.setText("0.00$");

        LabelTVQ.setText("0.00$");

        LabelTotal.setText("0.00$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(771, 771, 771)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelSubtotal)
                            .addComponent(LabelTPS)
                            .addComponent(LabelTVQ)
                            .addComponent(LabelTotal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonDelete)
                        .addComponent(ButtonAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelSubtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTPS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTVQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCancel)
                    .addComponent(ButtonOk))
                .addContainerGap())
        );

        LabelSubtotal.setHorizontalTextPosition(javax.swing.JLabel.RIGHT);
        LabelSubtotal.setVerticalTextPosition(javax.swing.JLabel.CENTER);
        LabelTPS.setHorizontalTextPosition(javax.swing.JLabel.RIGHT);
        LabelTPS.setVerticalTextPosition(javax.swing.JLabel.CENTER);
        LabelTVQ.setHorizontalTextPosition(javax.swing.JLabel.RIGHT);
        LabelTVQ.setVerticalTextPosition(javax.swing.JLabel.CENTER);
        LabelTotal.setHorizontalTextPosition(javax.swing.JLabel.RIGHT);
        LabelTotal.setVerticalTextPosition(javax.swing.JLabel.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
	private void updateRoomList(Room r, int diffInDays) {
		DefaultTableModel model = (DefaultTableModel) TableChamberList.getModel();
		model.addRow(new Object[] {r.getRoomNumber(), r.getCategorie().getName(), diffInDays, getRoomPrice(r) * diffInDays});
		updateTotal();
	}
	
	private double getRoomPrice(Room r) {
		return Hotel.getInstance().getRoomPrice(r, new Date());
	}
	
	private void updateTotal() {
		double subTotal = 0;
		for (int i = 0; i < TableChamberList.getModel().getRowCount(); ++i) {
			subTotal = ((Double)TableChamberList.getModel().getValueAt(i, 3)).doubleValue();
		}
		
		subTotal = Math.abs(subTotal);
		LabelSubtotal.setText(subTotal + "$");
		LabelTPS.setText(Math.round(TaxesSystem.calculateTPS(subTotal)) + "$");
		subTotal += TaxesSystem.calculateTPS(subTotal);
		LabelTVQ.setText(Math.round(TaxesSystem.calculateTVQ(subTotal)) + "$");
		subTotal += TaxesSystem.calculateTVQ(subTotal);
		LabelTotal.setText(subTotal + "$");
	}
	
	private int diffDate(Date older, Date newer) {
		return (int)(newer.getTime() - older.getTime()) / (1000 * 60 * 60 * 24);
	}
    
    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_ButtonAddActionPerformed
    	JTextField roomNo = new JTextField();
    	final JComponent[] inputs = new JComponent[] {
    	                new JLabel("Numéro de la chambre"),
    	                roomNo
    	};
    	JOptionPane.showMessageDialog(null, inputs, "Ajout de chambre", JOptionPane.PLAIN_MESSAGE);
    	int no = Integer.parseInt(roomNo.getText());
    	boolean found = false;

    	for (Stay stay : Agenda.getInstance().getStays()) {
    		if (stay.getRoom().getRoomNumber() == no) {
    			
    			int day = stay.getDepartureDate().getDate();
    			int month = stay.getDepartureDate().getMonth();
    			int year = stay.getDepartureDate().getYear();
    			int currentDay = new Date().getDate();
    			int currentMonth = new Date().getMonth();
    			int currentYear = new Date().getYear();
    			
    			if (!((day == currentDay) && (month == currentMonth) && (year == currentYear))) {
    				int reply = JOptionPane.showConfirmDialog(null, "Le séjour termine avant la date finale voulez-vous continuez?", "", JOptionPane.YES_NO_OPTION);
    			    if (reply == JOptionPane.YES_OPTION) {
    			    	stay.setDepartureDate(new Date());
    			    	updateRoomList(stay.getRoom(), diffDate(stay.getArrivalDate(), stay.getDepartureDate()));
    			    }
    			    found = true;
    			    break;
    			}
    			else {
    				updateRoomList(stay.getRoom(), diffDate(stay.getArrivalDate(), stay.getDepartureDate()));
    				found = true;
    			    break;
    			}
    		}
    	}
    	if (!found)
    		throw new Exception();
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
    	int rowIndex = TableChamberList.getSelectedRow();
    	if (rowIndex != -1) {
    		javax.swing.table.DefaultTableModel model = (DefaultTableModel) TableChamberList.getModel();
    		int id = (Integer) model.getValueAt(rowIndex, 0);
    		model.removeRow(rowIndex);
    		updateTotal();
    	}
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOkActionPerformed
    	new PaiementForm(Integer.parseInt(LabelTotal.getText().replace("$", "")), TableChamberList).setVisible(true);
    	this.dispose();
    }//GEN-LAST:event_ButtonOkActionPerformed

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
    	this.dispose();
    }//GEN-LAST:event_ButtonCancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactureForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonOk;
    private javax.swing.JLabel LabelSubtotal;
    private javax.swing.JLabel LabelTPS;
    private javax.swing.JLabel LabelTVQ;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JTable TableChamberList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    int diffInDays = 0;

}