/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReservationForm.java
 *
 * Created on May 25, 2012, 9:27:11 AM
 */

package hotel.gui;

import hotel.Client;
import hotel.Hotel;
import hotel.Room;
import hotel.StaySystem;
import hotel.util.RoomNotFound;
import hotel.util.ValidationException;

import java.util.Date;

import javax.swing.JOptionPane;

/**
 *
 * @author AJ86290
 */
public class NewStayNoReservationForm extends javax.swing.JFrame {

    /** Creates new form NewStayNoReservationForm */
    public NewStayNoReservationForm(StaySystem ss) {
        GUI.initLookAndFeel();
        initComponents();
        staySystem = ss;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        TextName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextTelephone = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ButtonStart = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();
        DateArrival = new com.toedter.calendar.JDateChooser();
        DateDeparture = new com.toedter.calendar.JDateChooser();
        
        try {
            javax.swing.text.MaskFormatter mf = new javax.swing.text.MaskFormatter("### ###-####");
            javax.swing.text.DefaultFormatterFactory factory = new javax.swing.text.DefaultFormatterFactory(mf);
            TextTelephone = new javax.swing.JFormattedTextField();
            TextTelephone.setFormatterFactory(factory);
        } catch (java.text.ParseException pe) {
            pe.printStackTrace();
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Démarrer séjour");
        setResizable(false);

        TextName.setEditable(true);

        jLabel1.setText("Nom:");

        TextTelephone.setEditable(true);

        jLabel2.setText("Télephone:");

        jLabel3.setText("Arrivée:");

        jLabel4.setText("Départ:");

        ButtonStart.setText("Démarrer");
        ButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartActionPerformed(evt);
            }
        });

        ButtonCancel.setText("Annuler");
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButtonStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateDeparture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(DateArrival, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(TextTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(TextName, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DateArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DateDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonStart)
                    .addComponent(ButtonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void ButtonStartActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	int idRoom = SelectRoomForm.showDialog(this, this, staySystem, (java.util.List<Room>)Hotel.getInstance().getRooms());
		
    	Client client = null;
		try {
			client = new Client(TextName.getText(), TextTelephone.getText());
		} catch (ValidationException e1) {
			e1.printStackTrace();
		}
		
    	if (idRoom != -1) {
			staySystem.startStay(DateArrival.getDate(), DateDeparture.getDate(), client);
			try {
				staySystem.confirmStay(idRoom);
				JOptionPane.showMessageDialog(null, "Le séjour a été enregistré.");
			} catch (RoomNotFound e) {
				JOptionPane.showMessageDialog(null, "La chambre sélectionné n'a pas été trouvé.");
			}
		}
    	
    	this.dispose();
    }                                          

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {                                             
        this.dispose();
    }                                            

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStayNoReservationForm(new StaySystem()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonStart;
    private com.toedter.calendar.JDateChooser DateArrival;
    private javax.swing.JTextField TextName;
    private javax.swing.JFormattedTextField TextTelephone;
    private com.toedter.calendar.JDateChooser DateDeparture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration
    private StaySystem staySystem;
    private javax.swing.text.MaskFormatter mask = null;
}

