/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectChamber.java
 *
 * Created on Jun 27, 2012, 6:14:29 PM
 */

package hotel.gui;

import java.awt.Component;
import java.awt.Frame;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

import hotel.Hotel;
import hotel.Room;
import hotel.StaySystem;

public class SelectRoomForm extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	/** Creates new form SelectChamber 
     * @param staySystem */
    public SelectRoomForm(List<Room> rooms) {
    	GUI.initLookAndFeel();
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) TableRooms.getModel();
        for (Room room : rooms) {
            model.addRow(new Object[] {room.getCategorie().getName(), room.getRoomNumber()});
        }
    }
    
    private SelectRoomForm(List<Room> rooms, Frame frame, Component locationComponent, StaySystem system) {
    	//super(frame, "Détail de réservation", true);
    	staySystem = system;
        setLocationRelativeTo(locationComponent);
        
        GUI.initLookAndFeel();
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) TableRooms.getModel();
        for (Room room : rooms) {
            model.addRow(new Object[] {room.getCategorie().getName(), room.getRoomNumber()});
        }
    }
    
    public static boolean showDialog(List<Room> rooms, Component frameComponent, Component locationComponent, StaySystem system) {
		Frame frame = JOptionPane.getFrameForComponent(frameComponent);
		dialog = new SelectRoomForm(rooms, frame, locationComponent, system);
		dialog.setVisible(true);
		//return dialog.saved;
		return true;
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableRooms = new javax.swing.JTable();
        ButtonCancel = new javax.swing.JButton();
        ButtonSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sélectionner chambre");
        setResizable(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        TableRooms.setModel(new DefaultTableModel(
            new Object [][] { },
            new String [] {"Catégorie", "Numéro de chambre"}
        ) {
            Class[] types = new Class [] {String.class, Integer.class};

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        
        TableRooms.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        jScrollPane1.setViewportView(TableRooms);

        ButtonCancel.setText("Annuler");
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	ButtonCancelActionPerformed(evt);
            }
        });

        ButtonSelect.setText("Sélectionner");
        ButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(ButtonSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCancel)
                    .addComponent(ButtonSelect))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>
    
    private void ButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCloseActionPerformed
    	
    }//GEN-LAST:event_ButtonCloseActionPerformed
    
private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCloseActionPerformed
    	this.dispose();
    }//GEN-LAST:event_ButtonCloseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectRoomForm(Hotel.getInstance().getRooms()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonSelect;
    private javax.swing.JTable TableRooms;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
	private static SelectRoomForm dialog;
	private StaySystem staySystem;

}
